'use strict';
const express = require('express');
const router = express.Router();
const { supabase } = require('../db/supabase');
const { requireAuth, requireRole } = require('../utils/auth');
const { analysePlayer } = require('../engines/compatibility');

const PLAN_LIMITS = {
  Core: { exports: 30 },
  Plus: { exports: 120 },
  Elite: { exports: 500 },
  Enterprise: { exports: 99999 }
};

function limitFor(plan) {
  return (PLAN_LIMITS[plan] || PLAN_LIMITS.Core).exports;
}

function clean(value) {
  return String(value == null ? '' : value).replace(/[<>]/g, '');
}

function htmlEscape(value) {
  return clean(value)
    .replace(/&/g, '&amp;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function money(value) {
  return 'GBP ' + Math.round(Number(value) || 0).toLocaleString('en-GB');
}

function playerName(player) {
  return [player.first_name, player.last_name].filter(Boolean).join(' ') || 'Player';
}

function pdfEscape(value) {
  return clean(value).replace(/\\/g, '\\\\').replace(/\(/g, '\\(').replace(/\)/g, '\\)');
}

function wrap(text, width) {
  const words = clean(text).split(/\s+/).filter(Boolean);
  const lines = [];
  let line = '';
  words.forEach(word => {
    if ((line + ' ' + word).trim().length > width && line) {
      lines.push(line);
      line = word;
    } else {
      line = (line + ' ' + word).trim();
    }
  });
  if (line) lines.push(line);
  return lines.length ? lines : [''];
}

function rowValue(rows, label) {
  const found = (rows || []).find(r => String(r[0] || '').toLowerCase() === String(label || '').toLowerCase());
  return found ? found[1] : '';
}

function pdfRgb(hex) {
  const safe = String(hex || '#ffffff').replace('#', '');
  const n = parseInt(safe.length === 3 ? safe.split('').map(c => c + c).join('') : safe, 16);
  const r = ((n >> 16) & 255) / 255;
  const g = ((n >> 8) & 255) / 255;
  const b = (n & 255) / 255;
  return r.toFixed(3) + ' ' + g.toFixed(3) + ' ' + b.toFixed(3);
}

function ratingPercent(text) {
  const m = String(text || '').match(/([0-9]+(?:\.[0-9]+)?)/);
  if (!m) return null;
  const n = Number(m[1]);
  if (!Number.isFinite(n)) return null;
  return Math.max(0, Math.min(100, n <= 10 ? n * 10 : n));
}

function ratingColor(pct) {
  if (pct == null) return '#30363d';
  if (pct >= 80) return '#1d9e75';
  if (pct >= 65) return '#00BCD4';
  if (pct >= 50) return '#FFC107';
  return '#f85149';
}

function buildPdf(title, sections) {
  const pages = [];
  let ops = [];
  let y = 692;
  let pageNo = 0;
  const snapshotRows = (sections[0] && sections[0].rows) || [];
  const heroCards = [
    { label: 'Overall', value: rowValue(snapshotRows, 'Overall rating') || '--', hint: 'Coach-rated output' },
    { label: 'Compatibility', value: rowValue(snapshotRows, 'Compatibility score') || '--', hint: 'ScoutLink team fit' },
    { label: 'Value', value: rowValue(snapshotRows, 'Estimated value') || rowValue(snapshotRows, 'Recruitment Value Estimate') || rowValue(snapshotRows, 'Training Value Estimate') || rowValue(snapshotRows, 'Development Value Index') || rowValue(snapshotRows, 'Estimated transfer value') || '--', hint: 'Decision-support estimate' }
  ];
  function fill(hex, x, yy, w, h) {
    ops.push(pdfRgb(hex) + ' rg ' + [x, yy, w, h].map(v => Number(v).toFixed(2)).join(' ') + ' re f');
  }
  function text(value, x, yy, size, bold, hex) {
    ops.push(pdfRgb(hex || '#ffffff') + ' rg BT /' + (bold ? 'F2' : 'F1') + ' ' + size + ' Tf ' + Number(x).toFixed(2) + ' ' + Number(yy).toFixed(2) + ' Td (' + pdfEscape(value) + ') Tj ET');
  }
  function startPage() {
    pageNo += 1;
    ops = [];
    pages.push(ops);
    y = 690;
    fill('#0d1117', 0, 0, 612, 792);
    fill('#101820', 0, 718, 612, 74);
    fill('#1d9e75', 0, 718, 8, 74);
    text('Scout', 42, 760, 24, true, '#ffffff');
    text('Link', 106, 760, 24, true, '#1d9e75');
    text('STRATEX ANALYTICS PLAYER DOSSIER', 42, 744, 8, false, '#8b949e');
    text(pageNo === 1 ? title : title + ' - continued', 42, y, 16, true, '#e6edf3');
    y -= 26;
  }
  function footer() {
    text('Generated by ScoutLink. Personal contact information is intentionally excluded.', 42, 34, 8, false, '#6b7280');
    text('Page ' + pageNo, 532, 34, 8, false, '#6b7280');
  }
  function ensure(space) {
    if (y < space) {
      footer();
      startPage();
    }
  }
  function drawHero() {
    fill('#111827', 42, y - 70, 528, 62);
    fill('#1d9e75', 42, y - 70, 4, 62);
    text('EXPORT SUMMARY', 56, y - 28, 8, true, '#8b949e');
    heroCards.forEach((card, idx) => {
      const x = 56 + idx * 166;
      fill('#07111f', x, y - 62, 154, 42);
      text(card.label.toUpperCase(), x + 10, y - 36, 7, true, '#8b949e');
      text(card.value, x + 10, y - 51, String(card.value).length > 18 ? 10 : 13, true, idx === 1 ? '#1d9e75' : '#ffffff');
      text(card.hint, x + 10, y - 61, 6, false, '#6b7280');
    });
    y -= 88;
  }
  function drawSectionHeader(heading) {
    ensure(94);
    fill('#161b22', 42, y - 10, 528, 26);
    fill('#1d9e75', 42, y - 10, 4, 26);
    text(String(heading || '').toUpperCase(), 54, y, 11, true, '#ffffff');
    y -= 32;
  }
  function drawInfoRows(rows) {
    for (let i = 0; i < rows.length; i += 2) {
      ensure(94);
      [rows[i], rows[i + 1]].filter(Boolean).forEach((row, idx) => {
        const x = idx === 0 ? 48 : 312;
        fill('#0a0f1e', x, y - 38, 246, 42);
        text(row[0], x + 10, y - 14, 7, true, '#8b949e');
        wrap(row[1], 32).slice(0, 2).forEach((line, lineIdx) => {
          text(line, x + 10, y - 28 - (lineIdx * 10), lineIdx ? 8 : 9, true, '#e6edf3');
        });
      });
      y -= 50;
    }
  }
  function drawRatingRows(rows) {
    for (let i = 0; i < rows.length; i += 2) {
      ensure(84);
      [rows[i], rows[i + 1]].filter(Boolean).forEach((row, idx) => {
        const x = idx === 0 ? 48 : 312;
        const pct = ratingPercent(row[1]);
        fill('#0a0f1e', x, y - 28, 246, 32);
        text(row[0], x + 10, y - 11, 8, true, '#d1d5db');
        text(row[1], x + 198, y - 11, 8, true, ratingColor(pct));
        fill('#1e2a3a', x + 10, y - 22, 184, 5);
        if (pct != null) fill(ratingColor(pct), x + 10, y - 22, 184 * pct / 100, 5);
      });
      y -= 40;
    }
  }
  function drawLines(lines) {
    (lines || []).forEach(line => {
      const wrapped = wrap(line, 82);
      const h = Math.max(34, 16 + wrapped.length * 12);
      ensure(h + 52);
      fill('#0a0f1e', 48, y - h + 4, 510, h);
      wrapped.forEach((txt, idx) => text(txt, 60, y - 16 - idx * 12, 8.5, idx === 0, '#dce3ea'));
      y -= h + 8;
    });
  }
  startPage();
  drawHero();
  sections.forEach(section => {
    drawSectionHeader(section.heading);
    if (section.rows && section.rows.length) {
      if (/attribute/i.test(section.heading)) drawRatingRows(section.rows);
      else drawInfoRows(section.rows);
    }
    drawLines(section.lines || []);
    y -= 12;
  });
  footer();
  const pageKids = [];
  const objects = [
    '1 0 obj << /Type /Catalog /Pages 2 0 R >> endobj',
    '',
    '3 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica >> endobj',
    '4 0 obj << /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >> endobj'
  ];
  pages.forEach((pageOps, idx) => {
    const pageObj = 5 + idx * 2;
    const contentObj = pageObj + 1;
    const content = pageOps.join('\n');
    pageKids.push(pageObj + ' 0 R');
    objects.push(pageObj + ' 0 obj << /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ' + contentObj + ' 0 R >> endobj');
    objects.push(contentObj + ' 0 obj << /Length ' + Buffer.byteLength(content, 'utf8') + ' >> stream\n' + content + '\nendstream endobj');
  });
  objects[1] = '2 0 obj << /Type /Pages /Kids [' + pageKids.join(' ') + '] /Count ' + pages.length + ' >> endobj';
  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach(obj => {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += obj + '\n';
  });
  const xref = Buffer.byteLength(pdf, 'utf8');
  pdf += 'xref\n0 ' + (objects.length + 1) + '\n';
  pdf += '0000000000 65535 f \n';
  offsets.slice(1).forEach(offset => {
    pdf += String(offset).padStart(10, '0') + ' 00000 n \n';
  });
  pdf += 'trailer << /Size ' + (objects.length + 1) + ' /Root 1 0 R >>\nstartxref\n' + xref + '\n%%EOF';
  return Buffer.from(pdf, 'utf8');
}

function buildExcelHtml(title, sections) {
  let html = '<html><head><meta charset="utf-8"><style>body{font-family:Arial,sans-serif;color:#102033;background:#fff}h1{background:#101820;color:#fff;padding:20px;margin:0 0 8px;border-left:8px solid #1d9e75}h2{color:#101820;margin:22px 0 8px;padding-bottom:6px;border-bottom:2px solid #1d9e75}table{border-collapse:collapse;width:100%;margin-bottom:18px}th{background:#eaf7f2;color:#102033;text-align:left;text-transform:uppercase;font-size:11px;letter-spacing:.04em}td,th{border:1px solid #cfd8dc;padding:9px;vertical-align:top}td{background:#fff}.note{color:#607d8b;margin:0 0 14px}.line{font-size:12px;color:#102033}.brand{color:#1d9e75}</style></head><body>';
  html += '<h1>Scout<span class="brand">Link</span> - ' + htmlEscape(title) + '</h1><p class="note">Generated by ScoutLink. Personal contact information is intentionally excluded.</p>';
  sections.forEach(section => {
    html += '<h2>' + htmlEscape(section.heading) + '</h2><table border="1" cellspacing="0" cellpadding="6">';
    (section.rows || []).forEach(row => {
      html += '<tr><th>' + htmlEscape(row[0]) + '</th><td>' + htmlEscape(row[1]) + '</td></tr>';
    });
    (section.lines || []).forEach(line => {
      html += '<tr><td colspan="2" class="line">' + htmlEscape(line) + '</td></tr>';
    });
    html += '</table>';
  });
  html += '</body></html>';
  return Buffer.from(html, 'utf8');
}

async function loadScout(userId) {
  const { data: scout, error } = await supabase
    .from('scouts')
    .select('id,scout_team_id,subscription_plan,exports_remaining,scout_preferences')
    .eq('id', userId)
    .single();
  if (error || !scout) {
    const e = new Error('Scout not found');
    e.status = 404;
    throw e;
  }
  return scout;
}

async function countTeamExports(scout) {
  let q = supabase.from('scout_exports').select('id', { count:'exact', head:true });
  if (scout.scout_team_id) q = q.eq('scout_team_id', scout.scout_team_id);
  else q = q.eq('scout_id', scout.id);
  const { count, error } = await q;
  if (error) throw error;
  return count || 0;
}

async function updateRemaining(scout, remaining) {
  if (scout.scout_team_id) {
    await supabase.from('scouts').update({ exports_remaining: remaining }).eq('scout_team_id', scout.scout_team_id);
  } else {
    await supabase.from('scouts').update({ exports_remaining: remaining }).eq('id', scout.id);
  }
}

async function loadScoutTeam(scout) {
  if (!scout.scout_team_id) return { tier: 5 };
  const { data } = await supabase.from('scout_teams').select('*').eq('id', scout.scout_team_id).maybeSingle();
  const prefs = scout.scout_preferences || {};
  const team = data || { tier: 5 };
  if (prefs.teamWeaknesses?.length) team.team_weaknesses = prefs.teamWeaknesses;
  if (prefs.roleExpectations?.length) team.role_expectations = prefs.roleExpectations;
  if (prefs.longTermGoals?.length) team.long_term_goals = prefs.longTermGoals;
  if (prefs.formation) team.formation = prefs.formation;
  if (prefs.playingStyle) team.playing_style = prefs.playingStyle;
  return team;
}

const EXPORT_ATTRS = [
  ['pace','Pace'], ['agility','Agility'], ['strength','Strength'], ['stamina','Stamina'], ['jumping','Jumping'], ['composure','Composure'],
  ['shooting','Shooting'], ['passing','Passing'], ['dribbling','Dribbling'], ['defending','Defending'], ['crossing','Crossing'], ['vision','Vision'],
  ['positioning','Positioning'], ['heading','Heading'], ['tackling','Tackling'],
  ['gk_diving','GK Diving'], ['gk_handling','GK Handling'], ['gk_kicking','GK Kicking'], ['gk_reflexes','GK Reflexes'], ['gk_positioning','GK Positioning'],
  ['gk_distribution','GK Distribution'], ['gk_communication','GK Communication'], ['gk_sweeping','GK Sweeping']
];

function ratingText(value) {
  const n = Number(value);
  if (!Number.isFinite(n) || n <= 0) return 'Not rated';
  return (n > 10 ? n / 10 : n).toFixed(1) + ' / 10';
}

function matchScoreText(m) {
  const home = m.home_score ?? m.team_score ?? m.team_goals ?? m.goals_for;
  const away = m.away_score ?? m.opponent_score ?? m.opponent_goals ?? m.goals_against;
  if (home == null || away == null) return 'Score not entered';
  return String(home) + '-' + String(away);
}

function matchResultText(m) {
  if (m.result) return clean(m.result).replace(/\b\w/g, c => c.toUpperCase());
  const home = Number(m.home_score ?? m.team_score ?? m.team_goals ?? m.goals_for);
  const away = Number(m.away_score ?? m.opponent_score ?? m.opponent_goals ?? m.goals_against);
  if (!Number.isFinite(home) || !Number.isFinite(away)) return '';
  return home > away ? 'Win' : home < away ? 'Loss' : 'Draw';
}

function predictionLines(prediction) {
  if (!prediction) return [];
  const result = prediction.result || {};
  const lines = ['Prediction type: ' + (prediction.prediction_type || result.type || 'Prediction')];
  (result.paragraphs || []).forEach(p => lines.push(p));
  if (result.summary) lines.push('Summary: ' + result.summary);
  if (result.seasons) result.seasons.forEach(s => lines.push('Year ' + s.year + ': overall ' + s.overall + '/100, value ' + (s.transferValueFormatted || money(s.transferValue)) + ', ' + s.rankingImpact));
  if (result.projection) result.projection.forEach(s => lines.push(s.horizon + ': value ' + s.projectedValueFormatted + ', total cost ' + s.totalCostFormatted + ', ROI ' + s.roiPercent + '%'));
  if (result.evidence) lines.push('Scenario score: ' + (result.scenarioScore || '--') + '/100. Recommendation: ' + (result.recommendation || '--') + '. Risk: ' + (result.risk || '--') + '.');
  return lines;
}

function profileSections(player, matches, analysis, prediction) {
  const name = playerName(player);
  const position = player.specific_position || player.primary_position || player.position_group || '';
  const isGk = String(player.position_group || position).toLowerCase().includes('goalkeeper') || String(position).toUpperCase() === 'GK';
  const valueLabel = player.age && Number(player.age) <= 11 ? 'Development Value Index' :
    player.age && Number(player.age) <= 14 ? 'Training Value Estimate' :
    player.age && Number(player.age) <= 16 ? 'Recruitment Value Estimate' : 'Estimated value';
  const rows = [
    ['Name', name],
    ['Club', player.team_name || ''],
    ['Position', position],
    ['Age group', player.age_group || ''],
    ['Foot', player.foot || ''],
    ['Nationality', player.nationality || ''],
    ['Overall rating', player.overall_rating || ''],
    [valueLabel, money(player.transfer_value)],
    ['Compatibility score', analysis ? analysis.compatibilityScore + '/100' : '']
  ];
  const matchLines = (matches || []).slice(0, 5).map(m => {
    return [
      m.match_date,
      m.opponent_name || m.opponent,
      matchScoreText(m),
      matchResultText(m),
      'Position ' + (m.position_played || m.specific_position || position || '--'),
      'Perf ' + (m.performance_score || '--') + '/100',
      'G ' + (m.goals || 0),
      'A ' + (m.assists || 0),
      'Cards ' + ((m.yellow_cards || 0) + (m.red_cards || 0))
    ].filter(Boolean).join(' | ');
  });
  const attrRows = EXPORT_ATTRS
    .filter(([key]) => isGk || !key.startsWith('gk_'))
    .map(([key, label]) => [label, ratingText(player[key])]);
  const sections = [
    { heading: 'Player Snapshot', rows },
    { heading: 'Coach Attribute Ratings', rows: attrRows },
    { heading: 'Recent Match Facts', lines: matchLines.length ? matchLines : ['No recent match facts recorded.'] },
    { heading: 'Compatibility Analysis', rows: analysis ? [
      ['Compatibility', analysis.compatibilityScore + '/100'],
      ['Match performance', analysis.matchPerformanceRating || 'Not available'],
      ['Data confidence', analysis.dataConfidence?.label || analysis.compatibilityBreakdown?.dataConfidence || 'Not available'],
      ['Technical profile', (analysis.compatibilityBreakdown?.technical || '--') + '/100'],
      ['Tactical fit', (analysis.compatibilityBreakdown?.tacticalFit || '--') + '/100'],
      ['Physical profile', (analysis.compatibilityBreakdown?.physicalProfile || '--') + '/100'],
      ['Match impact', (analysis.compatibilityBreakdown?.matchImpact || '--') + '/100']
    ] : [], lines: analysis ? [
      'ScoutLink compatibility is a decision-support score using the player profile, coach ratings, match evidence and the saved scout setup.'
    ] : ['Compatibility was not calculated.'] }
  ];
  if (prediction) {
    sections.splice(1, 0, {
      heading: 'Prediction',
      lines: predictionLines(prediction)
    });
  }
  return sections;
}

router.post('/player', requireAuth, requireRole('Scout'), async (req, res) => {
  try {
    const { playerId, format = 'PDF', source = 'profile', predictionLogId } = req.body;
    if (!playerId) return res.status(400).json({ error: 'playerId required' });
    const scout = await loadScout(req.user.id);
    const limit = limitFor(scout.subscription_plan || 'Core');
    const used = await countTeamExports(scout);
    const remaining = Math.max(0, limit - used);
    if (remaining <= 0) {
      return res.status(402).json({ error: 'You have reached your export cap. Please contact info@scoutlink.app or your CS Manager to increase your cap.', exportsRemaining: 0, planLimit: limit });
    }

    const { data: player, error: playerErr } = await supabase.from('players').select('*').eq('id', playerId).single();
    if (playerErr || !player) return res.status(404).json({ error: 'Player not found' });
    const { data: matches } = await supabase.from('match_facts').select('*').eq('player_id', playerId).order('match_date', { ascending: false }).limit(10);
    const team = await loadScoutTeam(scout);
    const analysis = analysePlayer(player, team, matches || [], scout.scout_preferences || {});
    let prediction = null;
    if (predictionLogId) {
      const { data } = await supabase.from('predictions_log').select('*').eq('id', predictionLogId).eq('scout_id', req.user.id).maybeSingle();
      prediction = data || null;
    }

    const title = 'ScoutLink ' + (source === 'prediction' ? 'Prediction Export' : 'Player Profile') + ' - ' + playerName(player);
    const sections = profileSections(player, matches || [], analysis, prediction);
    const isExcel = String(format).toUpperCase() === 'EXCEL' || String(format).toUpperCase() === 'XLS';
    const buffer = isExcel ? buildExcelHtml(title, sections) : buildPdf(title, sections);
    const extension = isExcel ? 'xls' : 'pdf';
    const filename = clean(playerName(player)).replace(/\s+/g, '-').toLowerCase() + '-' + source + '.' + extension;
    const mime = isExcel ? 'application/vnd.ms-excel' : 'application/pdf';

    const { data: log, error: logErr } = await supabase.from('scout_exports').insert({
      scout_id: req.user.id,
      scout_team_id: scout.scout_team_id || null,
      player_id: playerId,
      prediction_log_id: predictionLogId || null,
      export_type: isExcel ? 'Excel' : 'PDF',
      source,
      file_name: filename,
      payload: { title, player_id: playerId, source, prediction_log_id: predictionLogId || null }
    }).select().single();
    if (logErr) throw logErr;

    const remainingAfter = Math.max(0, remaining - 1);
    await updateRemaining(scout, remainingAfter);
    res.json({
      exportId: log?.id || null,
      filename,
      mime,
      contentBase64: buffer.toString('base64'),
      exportsRemaining: remainingAfter,
      planLimit: limit,
      teamUsed: used + 1
    });
  } catch(err) {
    console.error('[Exports]', err);
    res.status(err.status || 500).json({ error: err.status ? err.message : 'Internal server error' });
  }
});

router.post('/:id/redownload', requireAuth, requireRole('Scout'), async (req, res) => {
  try {
    const scout = await loadScout(req.user.id);
    let q = supabase.from('scout_exports').select('*').eq('id', req.params.id);
    if (scout.scout_team_id) q = q.eq('scout_team_id', scout.scout_team_id);
    else q = q.eq('scout_id', scout.id);
    const { data: exp, error: expErr } = await q.maybeSingle();
    if (expErr) throw expErr;
    if (!exp) return res.status(404).json({ error: 'Export not found' });

    const { data: player, error: playerErr } = await supabase.from('players').select('*').eq('id', exp.player_id).single();
    if (playerErr || !player) return res.status(404).json({ error: 'Player not found' });
    const { data: matches } = await supabase.from('match_facts').select('*').eq('player_id', exp.player_id).order('match_date', { ascending: false }).limit(10);
    const team = await loadScoutTeam(scout);
    const analysis = analysePlayer(player, team, matches || [], scout.scout_preferences || {});
    let prediction = null;
    if (exp.prediction_log_id) {
      const { data } = await supabase.from('predictions_log').select('*').eq('id', exp.prediction_log_id).maybeSingle();
      prediction = data || null;
    }

    const isExcel = String(exp.export_type).toUpperCase() === 'EXCEL' || String(exp.export_type).toUpperCase() === 'XLS';
    const title = 'ScoutLink ' + (exp.source === 'prediction' ? 'Prediction Export' : 'Player Profile') + ' - ' + playerName(player);
    const sections = profileSections(player, matches || [], analysis, prediction);
    const buffer = isExcel ? buildExcelHtml(title, sections) : buildPdf(title, sections);
    const extension = isExcel ? 'xls' : 'pdf';
    const filename = exp.file_name || clean(playerName(player)).replace(/\s+/g, '-').toLowerCase() + '-' + (exp.source || 'profile') + '.' + extension;
    const mime = isExcel ? 'application/vnd.ms-excel' : 'application/pdf';
    res.json({ filename, mime, contentBase64: buffer.toString('base64'), redownload: true });
  } catch(err) {
    console.error('[Exports redownload]', err);
    res.status(err.status || 500).json({ error: err.status ? err.message : 'Internal server error' });
  }
});

module.exports = router;
