
const routes=[
  {id:"home",name:"Homepage",path:"/scoutlink"},
  {id:"demo",name:"Demo",path:"/demo"},
  {id:"coaches",name:"Coaches",path:"/coaches"},
  {id:"scouts",name:"Scouts",path:"/scouts"},
  {id:"parents",name:"Parents & Players",path:"/parents-players"},
  {id:"safeguarding",name:"Safeguarding",path:"/safeguarding"},
  {id:"login",name:"Login",path:"/login"},
  {id:"about",name:"About",path:"/about"},
  {id:"contact",name:"Contact",path:"/contact"},
  {id:"careers",name:"Careers",path:"/careers"}
];

function header(active="",mobile=false){
  const navItems=[
    ["coaches","Coaches","/coaches"],
    ["scouts","Scouts","/scouts"],
    ["parents","Parents & Players","/parents-players"],
    ["safeguarding","Safeguarding","/safeguarding"],
    ["demo","Demo","/demo"]
  ];
  const navHtml=navItems.map(item=>`<a class="${active===item[0]?'active':''}" href="${item[2]}">${item[1]}</a>`).join("");
  const menuHtml=navHtml+`<a href="/register/scout">Request Scout Access</a><a class="primary" href="/register/coach">Register as Coach</a><a href="/login">Sign in</a>`;
  const primaryLabel=active==='scouts'?'Request Scout Access':'Register as Coach';
  const primaryHref=active==='scouts'?'/register/scout':'/register/coach';
  return `<header class="site-header"><a class="logo" href="/">Scout<span>Link</span></a>
  <nav class="nav" aria-label="ScoutLink public navigation">${navHtml}</nav>
  <div class="header-actions"><a class="btn ghost" href="/login">Sign in</a><a class="btn primary" href="${primaryHref}">${primaryLabel}</a></div>
  <button class="menu" type="button" data-public-menu-open aria-label="Open menu" aria-expanded="false"><span></span><span></span><span></span></button>
  <div class="public-menu-panel" data-public-menu-backdrop aria-hidden="true"><div class="public-menu-drawer" role="dialog" aria-modal="true" aria-label="ScoutLink menu">
  <div class="public-menu-head"><a class="logo" href="/">Scout<span>Link</span></a><button class="public-menu-close" type="button" data-public-menu-close aria-label="Close menu">&times;</button></div>
  <nav class="public-menu-links" aria-label="Mobile navigation">${menuHtml}</nav>
  <div class="public-menu-foot">Coach-led, scout-reviewed grassroots football intelligence by Stratex Analytics.</div>
  </div></div></header>`;
}
function footer(){
  return `<footer class="footer"><div class="footer-grid">
  <div class="footer-intro"><a class="logo" href="/">Scout<span>Link</span></a><p>Coach-led, scout-reviewed grassroots football intelligence by Stratex Analytics.</p></div>
  <div class="footer-col"><b>Product</b><a href="/coaches">Coaches</a><a href="/scouts">Scouts</a><a href="/demo">Demo</a><a href="/scoutlink/compatibility-score">Compatibility</a></div>
  <div class="footer-col"><b>Trust</b><a href="/safeguarding">Safeguarding</a><a href="/parent-guardian-notice">Parent / Guardian Notice</a><a href="/report-a-concern">Report a Concern</a><a href="/scout-verification">Scout Verification</a></div>
  <div class="footer-col"><b>Company</b><a href="/about">About</a><a href="/contact">Contact</a><a href="/careers">Careers</a><a href="/accessibility">Accessibility</a></div>
  <div class="footer-col"><b>Legal</b><a href="/privacy-policy">Privacy Policy</a><a href="/terms">Terms of Use</a><a href="/cookie-policy">Cookie Policy</a><a href="/privacy-request">Privacy Request</a></div>
  </div><div class="footer-bottom"><span>&copy; 2026 ScoutLink. Powered by Stratex Analytics.</span><span><a href="mailto:info@scoutlink.app">info@scoutlink.app</a></span></div></footer>`;
}
function portrait(type){
  if(type==="coach"){
    return `<div class="portrait" role="img" aria-label="Fictional demo coach Marcus Reed"><img src="/images/coach-demo.png" alt="Fictional demo coach Marcus Reed"></div>`;
  }
  return `<div class="portrait" role="img" aria-label="Fictional demo scout Noah Patel"><img src="/images/scout-demo.png" alt="Fictional demo scout Noah Patel"></div>`;
}
function playerVisual(){
 return `<div class="hero-visual"><div class="player-head"><div class="person-line"><div class="avatar">EC</div><div><h3>Ethan Cole</h3><p>ST · U16 · Northgate United</p></div></div><div class="score">82<small>Compatibility</small></div></div>
 ${[["Overall rating",78],["Match evidence",84],["Data confidence",72],["Development upside",88]].map(x=>`<div class="metric"><div class="metric-lab"><span>${x[0]}</span><b>${x[1]}</b></div><div class="bar"><span style="width:${x[1]}%"></span></div></div>`).join("")}
 <div class="stats"><div class="stat"><b>5</b><span>Match facts</span></div><div class="stat"><b>High</b><span>Coach evidence</span></div><div class="stat"><b>Current</b><span>Profile status</span></div></div></div>`;
}
function trustBand(){
 return `<section class="section band"><div><span class="pill dark">Trust and safeguarding</span><h2>Player visibility should never feel uncontrolled.</h2><p>Scout access is reviewed, player information stays inside controlled product workflows and interest is routed through coaches, clubs and responsible adults.</p></div><div class="band-links"><div class="band-link"><span>Safeguarding</span><span>→</span></div><div class="band-link"><span>Parent / Guardian Notice</span><span>→</span></div><div class="band-link"><span>Report a Concern</span><span>→</span></div></div></section>`;
}
function commonCTA(title="Build better player evidence.",copy="Create a free coach account or explore ScoutLink before you register."){
 return `<section class="section cta"><div><span class="pill green">Ready when your team is</span><h2>${title}</h2><p>${copy}</p></div><div class="cta-actions"><a class="btn primary" href="/register/coach">Register as Coach</a><a class="btn" href="/demo">Explore Demo</a><a class="btn ghost" href="/register/scout">Request Scout Access</a></div></section>`;
}
function mobileSticky(primary="Register as Coach"){
 const label=primary.toLowerCase();
 const href=label.includes("concern")?"/report-a-concern":label.includes("notice")?"/parent-guardian-notice":label.includes("role")?"#careerRoleList":label.includes("message")?"#publicContactForm":"/register/coach";
 return `<div class="mobile-sticky"><a class="btn primary" href="${href}">${primary}</a><a class="btn" href="/demo">Demo</a></div>`;
}
function homePage(m){
 return `<div class="page">${header("home",m)}<section class="hero"><div><span class="pill white">Grassroots football intelligence</span><h1>Make player evidence easier to trust, find and act on.</h1><p class="lead">ScoutLink helps grassroots coaches organise player profiles, ratings, match facts, fixtures and approved video evidence so reviewed scouts can search, compare and shortlist U7–U16 players with better context.</p><div class="hero-actions"><button class="btn primary">Register as Coach</button><button class="btn">Explore Demo</button><button class="btn ghost">Request Scout Access →</button></div><div class="hero-pills"><span class="pill green">Free coach workspace</span><span class="pill blue">Reviewed scout access</span><span class="pill grey">Adult-led contact</span></div></div>${playerVisual()}</section>
 <main class="main">
 <section class="section"><div class="section-title"><div><span class="pill white">How ScoutLink works</span><h2>Three steps from local knowledge to better scouting context.</h2></div><p>One clear journey connects the people creating evidence with the people reviewing it.</p></div><div class="steps"><article class="step"><div class="step-no">01</div><h3>Coaches build evidence</h3><p>Profiles, ratings, match facts, fixtures and approved video sit in one structured player record.</p></article><article class="step"><div class="step-no">02</div><h3>Scouts search by fit</h3><p>Reviewed scouts use structured filters and compatibility context to find relevant players.</p></article><article class="step"><div class="step-no">03</div><h3>Interest is handled safely</h3><p>Follow-up is routed through responsible adults, teams and clubs.</p></article></div></section>
 <section class="section feature-showcase"><div><span class="pill green">Product intelligence</span><h2 style="font-size:28px;line-height:1.03;letter-spacing:-1px;margin:9px 0 7px">One football workflow, not six disconnected tools.</h2><p style="font-size:9px;color:var(--muted);line-height:1.55">Bring player profiles, match evidence, comparison, compatibility and recruitment decisions into one evidence-led experience.</p><button class="btn" style="margin-top:12px">Explore the Demo</button></div><div><div class="tabs"><button class="tab active">Player profile</button><button class="tab">Compatibility</button><button class="tab">Scout search</button><button class="tab">Match facts</button><button class="tab">Pipeline</button></div><div class="product-panel"><span class="pill dark">PLAYER PROFILE</span><h3>One structured record for the player.</h3><p>Ratings, match facts, fixtures, approved video, physical context and evidence confidence sit together.</p><div class="mini-grid"><div class="mini"><b>Ratings</b><span>Coach-led attributes</span></div><div class="mini"><b>Match facts</b><span>Game evidence</span></div><div class="mini"><b>Video</b><span>Approved clips</span></div><div class="mini"><b>Confidence</b><span>Evidence quality</span></div></div></div></div></section>
 <section class="section"><div class="section-title"><div><span class="pill white">Built around the football network</span><h2>Different roles, one shared evidence standard.</h2></div></div><div class="grid cols4"><article class="card"><div class="icon green">CO</div><h4 style="margin-top:10px">Coaches</h4><p>Create player profiles, update evidence and manage scout interest.</p></article><article class="card"><div class="icon">SC</div><h4 style="margin-top:10px">Scouts</h4><p>Search, compare, shortlist and manage a recruitment pipeline.</p></article><article class="card"><div class="icon orange">CL</div><h4 style="margin-top:10px">Clubs and academies</h4><p>Bring team context and player evidence into one accountable process.</p></article><article class="card"><div class="icon">FA</div><h4 style="margin-top:10px">Families</h4><p>Understand visibility, access and how to raise a concern.</p></article></div></section>
 ${trustBand()}${commonCTA()}
 <section class="section"><div class="section-title"><div><span class="pill white">Common questions</span><h2>Before you start.</h2></div></div><div class="faq-item"><span>Who is ScoutLink for?</span><span class="plus">+</span></div><div class="faq-item"><span>Can anyone browse players?</span><span class="plus">+</span></div><div class="faq-item"><span>Does compatibility replace scout judgement?</span><span class="plus">+</span></div></section>
 </main>${footer()}${m?mobileSticky():""}</div>`;
}
function demoPage(m){
 return `<div class="page">${header("demo",m)}<section class="hero dark"><div><span class="pill dark">Fictional product demo</span><h1>See how ScoutLink works before you register.</h1><p class="lead">Explore realistic coach player-management workflows and reviewed scout recruitment tools using isolated fictional data. Demo actions never change live product records.</p><div class="hero-actions"><button class="btn primary">Explore as Coach</button><button class="btn">Explore as Scout</button></div><div class="hero-pills"><span class="pill dark">No account required</span><span class="pill dark">Fictional data</span><span class="pill dark">Safe demo environment</span></div></div>${playerVisual()}</section>
 <main class="main">
 <section class="section"><div class="section-title"><div><span class="pill white">Choose a demo</span><h2>Two focused journeys, without oversized cards.</h2></div><p>Each route opens with seeded records, guided prompts and no impact on production data.</p></div>
 <div class="demo-cards">
 <article class="card demo-card">${portrait("coach")}<div class="portrait-copy"><span class="pill green">Coach demo</span><h3>Marcus Reed</h3><p>Manage a fictional squad, add player evidence, create fixtures, record match facts and review scout interest.</p><div class="tag-list"><span class="pill grey">Profiles</span><span class="pill grey">Fixtures</span><span class="pill grey">Match facts</span></div><button class="btn primary sm">Start coach demo</button></div></article>
 <article class="card demo-card">${portrait("scout")}<div class="portrait-copy"><span class="pill blue">Scout demo</span><h3>Noah Patel</h3><p>Search and compare fictional players, review compatibility and manage a recruitment pipeline.</p><div class="tag-list"><span class="pill grey">Search</span><span class="pill grey">Comparison</span><span class="pill grey">Pipeline</span></div><button class="btn dark sm">Start scout demo</button></div></article>
 </div></section>
 <section class="section"><div class="section-title"><div><span class="pill white">What the demo shows</span><h2>A clear look at the real workflows.</h2></div><p>ScoutLink supports grassroots discovery before players are fully represented in traditional professional football databases.</p></div><div class="grid cols3"><article class="card"><div class="icon green">01</div><h4 style="margin-top:10px">Coach-led evidence</h4><p>Profiles, match facts, fixtures and approved video are maintained by teams.</p></article><article class="card"><div class="icon">02</div><h4 style="margin-top:10px">Compatibility support</h4><p>Scouts compare player fit, team needs and evidence confidence while keeping final judgement human.</p></article><article class="card"><div class="icon orange">03</div><h4 style="margin-top:10px">Controlled contact</h4><p>Interest and recruitment workflows remain coach-mediated and adult-led.</p></article></div></section>
 <section class="section feature-showcase"><div><span class="pill green">Guided product tour</span><h2 style="font-size:28px;line-height:1.03;margin:9px 0 7px">See evidence, decisions and next actions together.</h2><p style="font-size:9px;color:var(--muted)">The demo should show the product, not overwhelm users with explanation before they enter it.</p></div><div class="product-panel"><span class="pill dark">DEMO CHECKLIST</span><h3>Try the important moments.</h3><div class="mini-grid"><div class="mini"><b>Add evidence</b><span>Coach workflow</span></div><div class="mini"><b>Search players</b><span>Scout filters</span></div><div class="mini"><b>Compare fit</b><span>Compatibility</span></div><div class="mini"><b>Shortlist</b><span>Pipeline</span></div></div></div></section>
 ${trustBand()}${commonCTA("Ready to explore ScoutLink?","Use the fictional demo first, then choose the coach or scout registration route that fits you.")}
 </main>${footer()}${m?mobileSticky("Start Coach Demo"):""}</div>`;
}
function coachesPage(m){
 return `<div class="page">${header("coaches",m)}<section class="hero"><div><span class="pill green">For grassroots coaches</span><h1>Build better player profiles without creating more admin.</h1><p class="lead">ScoutLink helps coaches organise U7–U16 player evidence through match facts, ratings, fixtures, video and development context so reviewed scouts can understand more than a forwarded clip.</p><div class="hero-actions"><button class="btn primary">Register as Coach</button><button class="btn">Explore Coach Demo</button><button class="btn ghost">Read Safeguarding</button></div><div class="hero-pills"><span class="pill green">Free coach workspace</span><span class="pill grey">Team-level evidence</span><span class="pill blue">Controlled scout interest</span></div></div>
 <div class="hero-visual light"><span class="pill green">Coach evidence health</span><h3 style="font-size:22px;margin:14px 0 5px">Northgate United U16</h3><p style="font-size:9px;color:var(--muted)">18 players · 3 upcoming fixtures</p><div class="stats"><div class="stat"><b>14</b><span>Profiles ready</span></div><div class="stat"><b>76%</b><span>Evidence complete</span></div><div class="stat"><b>4</b><span>Actions due</span></div></div>${[["Player details",90],["Match facts",72],["Video evidence",58]].map(x=>`<div class="metric"><div class="metric-lab"><span>${x[0]}</span><b>${x[1]}%</b></div><div class="bar"><span style="width:${x[1]}%"></span></div></div>`).join("")}</div></section>
 <main class="main">
 <section class="section"><div class="section-title"><div><span class="pill white">What coaches can do</span><h2>Keep player context useful and current.</h2></div><p>The workflow should feel like a simple team-management habit, not a scouting administration burden.</p></div><div class="grid cols3"><article class="card"><div class="icon green">01</div><h4 style="margin-top:10px">Create structured profiles</h4><p>Store positions, physical context, coach-rated attributes, videos and profile completion together.</p></article><article class="card"><div class="icon">02</div><h4 style="margin-top:10px">Add match evidence</h4><p>Record fixtures, match facts, ratings and performance context game by game.</p></article><article class="card"><div class="icon orange">03</div><h4 style="margin-top:10px">Handle scout interest</h4><p>Receive and manage reviewed scout interest through safer adult-led routes.</p></article></div></section>
 <section class="section"><div class="section-title"><div><span class="pill white">A practical weekly workflow</span><h2>Update the evidence in three short moments.</h2></div></div><div class="steps"><article class="step"><div class="step-no">01</div><h3>Before the match</h3><p>Add fixtures, player availability and the expected squad context.</p></article><article class="step"><div class="step-no">02</div><h3>After the match</h3><p>Add match facts, ratings and the most useful coach observations.</p></article><article class="step"><div class="step-no">03</div><h3>Keep profiles ready</h3><p>Review missing evidence and manage any scout interest from one dashboard.</p></article></div></section>
 <section class="section feature-showcase"><div><span class="pill green">Evidence overview</span><h2 style="font-size:28px;line-height:1.03;margin:9px 0 7px">See what is complete before a scout does.</h2><p style="font-size:9px;color:var(--muted)">Make missing context visible, prioritise the strongest actions and avoid profile gaps.</p></div><div class="product-panel"><span class="pill dark">TEAM DASHBOARD</span><h3>Four evidence tasks need attention.</h3><div class="mini-grid"><div class="mini"><b>Profiles</b><span>14 of 18 ready</span></div><div class="mini"><b>Fixtures</b><span>3 upcoming</span></div><div class="mini"><b>Match facts</b><span>2 missing</span></div><div class="mini"><b>Video</b><span>6 approved reels</span></div></div></div></section>
 ${trustBand()}${commonCTA("Create your free coach workspace.","Register your team, add players and begin building structured football evidence.")}
 <section class="section"><div class="section-title"><div><span class="pill white">Coach questions</span><h2>What coaches usually ask first.</h2></div></div><div class="faq-item"><span>How much does a coach account cost?</span><span class="plus">+</span></div><div class="faq-item"><span>How much time does profile maintenance take?</span><span class="plus">+</span></div><div class="faq-item"><span>How is scout interest handled?</span><span class="plus">+</span></div></section>
 </main>${footer()}${m?mobileSticky():""}</div>`;
}
function scoutsPage(m){
 return `<div class="page">${header("scouts",m)}<section class="hero dark"><div><span class="pill dark">For reviewed football scouts</span><h1>Better evidence. Better scouting context.</h1><p class="lead">Search, compare and shortlist U7–U16 grassroots players using coach-led profiles, match facts, approved video and explainable compatibility decision support.</p><div class="hero-actions"><button class="btn primary">Request Scout Access</button><button class="btn">Explore Scout Demo</button><button class="btn ghost" style="color:#fff;border-color:rgba(255,255,255,.18)">For Coaches</button></div><div class="hero-pills"><span class="pill dark">Reviewed access</span><span class="pill dark">Search and compare</span><span class="pill dark">Coach-mediated interest</span></div></div>${playerVisual()}</section>
 <main class="main">
 <section class="section"><div class="section-title"><div><span class="pill white">Scout workflows</span><h2>Built around evidence, fit and accountable next steps.</h2></div><p>Use grassroots context alongside established recruitment systems when professional-market data is missing.</p></div><div class="steps"><article class="step"><div class="step-no">01</div><h3>Search by evidence</h3><p>Filter by position, age group, location, rating, compatibility and evidence confidence.</p></article><article class="step"><div class="step-no">02</div><h3>Compare with context</h3><p>Review attributes, match output, physical context, video and team fit together.</p></article><article class="step"><div class="step-no">03</div><h3>Shortlist safely</h3><p>Build a pipeline and route interest through coaches and responsible adults.</p></article></div></section>
 <section class="section grid cols2"><article class="card"><span class="pill green">Compatibility</span><h3 style="font-size:24px;margin-top:11px">Understand why a player may fit.</h3><p>Compare team weaknesses, role expectations, tactical style, formation, development pathway and evidence confidence without replacing scout judgement.</p><div class="tag-list"><span class="pill grey">Team need</span><span class="pill grey">Role fit</span><span class="pill grey">Evidence</span></div></article><article class="card"><span class="pill blue">Reviewed access</span><h3 style="font-size:24px;margin-top:11px">Search is controlled, not public.</h3><p>Identity, organisation details and required documents are reviewed before access to player search and recruitment workflows is granted.</p><div class="tag-list"><span class="pill grey">Identity review</span><span class="pill grey">DBS document</span><span class="pill grey">Role context</span></div></article></section>
 <section class="section feature-showcase"><div><span class="pill green">Recruitment pipeline</span><h2 style="font-size:28px;line-height:1.03;margin:9px 0 7px">Keep discovery, comparison and follow-up connected.</h2><p style="font-size:9px;color:var(--muted)">Move relevant players through a visible recruitment workflow rather than leaving decisions in scattered notes.</p></div><div class="product-panel"><span class="pill dark">SCOUT PIPELINE</span><h3>12 players under review.</h3><div class="mini-grid"><div class="mini"><b>Discovered</b><span>12 players</span></div><div class="mini"><b>Compared</b><span>7 players</span></div><div class="mini"><b>Shortlisted</b><span>4 players</span></div><div class="mini"><b>Interest sent</b><span>2 coaches</span></div></div></div></section>
 ${trustBand()}${commonCTA("Ready to search with better context?","Request reviewed ScoutLink access or explore the scout demo using fictional records.")}
 </main>${footer()}${m?mobileSticky("Request Scout Access"):""}</div>`;
}
function parentsPage(m){
 return `<div class="page">${header("parents",m)}<section class="hero"><div><span class="pill green">Parents and players</span><h1>Helping grassroots players get seen more safely.</h1><p class="lead">ScoutLink represents U7–U16 players through coach-led profiles, structured football evidence and reviewed scout access rather than open self-promotion or direct scout-to-child contact.</p><div class="hero-actions"><button class="btn primary">Parent / Guardian Notice</button><button class="btn">Safeguarding</button><button class="btn ghost">Report a Concern</button></div></div>
 <div class="hero-visual light"><span class="pill green">What families should know</span><div class="notice-list" style="margin-top:14px"><div class="notice">Player information should be added only by authorised adults with the correct permissions or notices in place.</div><div class="notice">Compatibility is decision support. It does not decide a child's value, ability or future.</div><div class="notice">Privacy, safeguarding and concern routes remain publicly available.</div></div></div></section>
 <main class="main">
 <section class="section"><div class="section-title"><div><span class="pill white">How the experience is protected</span><h2>Clear responsibilities at every stage.</h2></div></div><div class="grid cols3"><article class="card"><div class="icon green">01</div><h4 style="margin-top:10px">Coach-led profiles</h4><p>Profiles are built by authorised adults around football evidence, not children promoting themselves.</p></article><article class="card"><div class="icon">02</div><h4 style="margin-top:10px">Reviewed scout access</h4><p>Player search is controlled so visibility is not an open public directory.</p></article><article class="card"><div class="icon orange">03</div><h4 style="margin-top:10px">Clear concern routes</h4><p>Families can report safeguarding, privacy, conduct or access concerns publicly.</p></article></div></section>
 <section class="section grid cols2"><article class="card"><span class="pill green">What can be included</span><h3 style="font-size:23px;margin-top:10px">Football evidence and development context.</h3><p>Position, age group, attributes, match facts, fixtures, approved video and other football information maintained by the responsible team.</p></article><article class="card"><span class="pill blue">What is not supported</span><h3 style="font-size:23px;margin-top:10px">Open contact or guaranteed outcomes.</h3><p>ScoutLink does not promise trials, contracts or selection and does not support open direct scout-to-child messaging.</p></article></section>
 ${trustBand()}
 <section class="section"><div class="section-title"><div><span class="pill white">Frequently asked questions</span><h2>Answers for families.</h2></div></div><div class="faq-item"><span>Can ScoutLink guarantee a player will be scouted?</span><span class="plus">+</span></div><div class="faq-item"><span>Who creates and manages player profiles?</span><span class="plus">+</span></div><div class="faq-item"><span>How can a family raise a concern?</span><span class="plus">+</span></div></section>
 ${commonCTA("Read the Parent / Guardian Notice.","Understand the information, permissions, visibility and contact routes connected to ScoutLink.")}
 </main>${footer()}${m?mobileSticky("Parent Notice"):""}</div>`;
}
function safeguardingPage(m){
 return `<div class="page">${header("safeguarding",m)}<section class="hero dark"><div><span class="pill dark">Safeguarding at ScoutLink</span><h1>Built for youth football, with controlled visibility in mind.</h1><p class="lead">ScoutLink combines coach-led evidence, reviewed scout access, adult-mediated interest, visible reporting routes and clear limits around how youth-player information can be used.</p><div class="hero-actions"><button class="btn primary">Report a Concern</button><button class="btn">Parent / Guardian Notice</button><button class="btn ghost" style="color:#fff;border-color:rgba(255,255,255,.18)">Privacy Policy</button></div></div><div class="hero-visual"><div class="shield"></div><div style="text-align:center;margin-top:8px"><b style="font-size:14px">Controlled by design</b><p style="font-size:8px;color:#c6d3e0">Reviewed access · adult-led contact · clear escalation</p></div></div></section>
 <main class="main">
 <section class="section"><div class="section-title"><div><span class="pill white">Safeguarding principles</span><h2>Three controls shape the whole product.</h2></div><p>Safeguarding should not be hidden inside one policy page. It must appear throughout the product journey.</p></div><div class="grid cols3"><article class="card"><div class="icon green">01</div><h4 style="margin-top:10px">Coach-led evidence</h4><p>Profiles should be created and managed by authorised adults, teams, schools or approved programmes.</p></article><article class="card"><div class="icon">02</div><h4 style="margin-top:10px">Reviewed scout access</h4><p>Scout access is request-based and can be reviewed, restricted or removed where concerns arise.</p></article><article class="card"><div class="icon orange">03</div><h4 style="margin-top:10px">Controlled visibility</h4><p>Player information stays inside the product and should not be scraped, exported or shared without permission.</p></article></div></section>
 <section class="section"><div class="section-title"><div><span class="pill white">How access works</span><h2>Review before visibility.</h2></div></div><div class="timeline"><article class="timeline-item"><b>1. Application</b><p>The scout provides identity, organisation and professional-role information.</p></article><article class="timeline-item"><b>2. Documents</b><p>Required identity and DBS documentation is submitted for review.</p></article><article class="timeline-item"><b>3. Internal review</b><p>Stratex staff approve or decline the requested ScoutLink access.</p></article><article class="timeline-item"><b>4. Ongoing control</b><p>Permissions, concern routes and account restrictions remain available.</p></article></div></section>
 <section class="section grid cols2"><article class="card"><span class="pill green">Adult-mediated contact</span><h3 style="font-size:23px;margin-top:10px">Interest should move through responsible adults.</h3><p>Coach, club, school or guardian-led routes should remain central to player visibility and follow-up.</p></article><article class="card"><span class="pill orange">Report and escalation</span><h3 style="font-size:23px;margin-top:10px">Concerns need a clear route.</h3><p>Users should be able to report inappropriate contact, suspected misuse, inaccurate access or another safety issue.</p></article></section>
 <section class="section band"><div><span class="pill dark">Need to report something?</span><h2>Use the dedicated concern route.</h2><p>Immediate danger should be reported to emergency services or the appropriate safeguarding authority first.</p></div><div class="band-links"><div class="band-link"><span>Report a Concern</span><span>→</span></div><div class="band-link"><span>Parent / Guardian Notice</span><span>→</span></div><div class="band-link"><span>Contact ScoutLink</span><span>→</span></div></div></section>
 <section class="section"><div class="section-title"><div><span class="pill white">Safeguarding questions</span><h2>Clear answers, not vague promises.</h2></div></div><div class="faq-item"><span>Can scouts contact children directly?</span><span class="plus">+</span></div><div class="faq-item"><span>Who can create player profiles?</span><span class="plus">+</span></div><div class="faq-item"><span>What happens after a concern is submitted?</span><span class="plus">+</span></div></section>
 </main>${footer()}${m?mobileSticky("Report a Concern"):""}</div>`;
}
function loginPage(m){
 return `<div class="page">${header("login",m)}<main class="login-layout">
 <section class="login-brand"><div><span class="pill dark">ScoutLink sign in</span><h1>Return to the workspace built for your role.</h1><p>Coaches manage player evidence. Reviewed scouts search and compare. Internal users support the product and its trust workflows.</p><div class="login-points"><div class="login-point"><span class="dot"></span><span>Coach-led player evidence and football-development records.</span></div><div class="login-point"><span class="dot"></span><span>Reviewed scout access and controlled visibility.</span></div><div class="login-point"><span class="dot"></span><span>Compatibility decision support without replacing judgement.</span></div></div></div><div class="tag-list"><span class="pill dark">Coach registration</span><span class="pill dark">Scout access</span><span class="pill dark">Safeguarding</span></div></section>
 <section class="login-card"><span class="pill green">Secure account access</span><h2 style="margin-top:12px">Sign in to ScoutLink</h2><p>Use your email and password, or the login code from your approval or invitation email.</p><div class="login-tabs"><button class="login-tab active">Email and password</button><button class="login-tab">Login with code</button></div><div class="field"><label>Email address</label><div class="input">your@email.com</div></div><div class="field" style="margin-top:11px"><label>Password</label><div class="input">Enter your password</div></div><button class="btn primary block" style="margin-top:13px">Sign in</button><button class="btn ghost block" style="margin-top:7px;color:var(--green2)">Forgot password?</button><div style="height:1px;background:var(--line);margin:15px 0"></div><p style="text-align:center;margin:0">New to ScoutLink? <b style="color:var(--green2)">Choose a registration route</b></p></section>
 </main><section class="main" style="padding-top:0"><div class="grid cols3"><article class="card flat"><h4>Coach registration</h4><p>Create a free coach workspace and begin setting up your team.</p></article><article class="card flat"><h4>Scout access</h4><p>Apply for reviewed access to player search, comparison and pipelines.</p></article><article class="card flat"><h4>Access help</h4><p>Get support with an invitation, approval code or account issue.</p></article></div></section>${footer()}</div>`;
}
function aboutPage(m){
 return `<div class="page">${header("about",m)}<section class="hero"><div><span class="pill green">About Stratex Analytics</span><h1>Building better football intelligence for overlooked talent.</h1><p class="lead">Stratex Analytics creates products that turn local football knowledge into structured evidence, clearer scouting context and safer routes between coaches, players and decision-makers.</p><div class="hero-actions"><button class="btn primary">Explore ScoutLink</button><button class="btn">Meet the Team</button><button class="btn ghost">Contact Stratex</button></div></div><div class="hero-visual light"><span class="pill green">Our focus</span><h3 style="font-size:24px;margin:14px 0 7px">Grassroots evidence that can travel further.</h3><p style="font-size:9px;color:var(--muted);line-height:1.55">ScoutLink is the first product in a broader football-intelligence vision centred on evidence, fit and responsible visibility.</p><div class="stats"><div class="stat"><b>Product</b><span>ScoutLink</span></div><div class="stat"><b>Market</b><span>Youth football</span></div><div class="stat"><b>Approach</b><span>Data-led</span></div></div></div></section>
 <main class="main">
 <section class="section"><div class="section-title"><div><span class="pill white">Why Stratex exists</span><h2>Talent should not depend only on who happens to be watching.</h2></div><p>Grassroots players are often described through memory, messages and isolated clips rather than useful, current context.</p></div><div class="grid cols3"><article class="card"><div class="icon green">01</div><h4 style="margin-top:10px">Organise the evidence</h4><p>Give coaches a simple way to structure the information they already know.</p></article><article class="card"><div class="icon">02</div><h4 style="margin-top:10px">Improve the decision context</h4><p>Help scouts compare players against real team needs and role expectations.</p></article><article class="card"><div class="icon orange">03</div><h4 style="margin-top:10px">Keep visibility responsible</h4><p>Build adult-led routes, reviewed access and clear concern processes into the experience.</p></article></div></section>
 <section class="section feature-showcase"><div><span class="pill green">Our flagship product</span><h2 style="font-size:28px;line-height:1.03;margin:9px 0 7px">ScoutLink connects evidence with discovery.</h2><p style="font-size:9px;color:var(--muted)">Coaches build the record. Scouts review the context. Families understand how visibility works.</p><button class="btn primary" style="margin-top:12px">Explore ScoutLink</button></div><div class="product-panel"><span class="pill dark">SCOUTLINK</span><h3>Coach-led. Scout-reviewed. Youth football, properly.</h3><div class="mini-grid"><div class="mini"><b>Profiles</b><span>Structured evidence</span></div><div class="mini"><b>Search</b><span>Reviewed access</span></div><div class="mini"><b>Fit</b><span>Compatibility</span></div><div class="mini"><b>Trust</b><span>Controlled routes</span></div></div></div></section>
 <section class="section"><div class="section-title"><div><span class="pill white">How we work</span><h2>Close to the users, evidence and football problem.</h2></div></div><div class="timeline"><article class="timeline-item"><b>Listen</b><p>Understand coaches, scouts and the points where existing workflows break.</p></article><article class="timeline-item"><b>Structure</b><p>Turn football knowledge into clear data and product decisions.</p></article><article class="timeline-item"><b>Build</b><p>Create useful workflows without hiding trust requirements.</p></article><article class="timeline-item"><b>Improve</b><p>Use feedback and product evidence to refine what works.</p></article></div></section>
 ${trustBand()}${commonCTA("Explore what Stratex is building.","See ScoutLink, meet the leadership team or start a conversation with Stratex Analytics.")}
 </main>${footer()}${m?mobileSticky("Explore ScoutLink"):""}</div>`;
}
function contactPage(m){
 return `<div class="page">${header("contact",m)}<section class="hero"><div><span class="pill green">Contact ScoutLink</span><h1>Talk to the right Stratex team.</h1><p class="lead">Use this page for ScoutLink support, coach onboarding, scout access, privacy, accessibility, careers, partnerships or general Stratex Analytics enquiries.</p><div class="hero-actions"><button class="btn primary">Send a Message</button><button class="btn">Report a Concern</button><button class="btn ghost">Privacy Request</button></div></div><div class="hero-visual light"><span class="pill green">Useful routes</span><div class="notice-list" style="margin-top:14px"><div class="notice"><b>Urgent safety concern</b><br>Use Report a Concern or the appropriate emergency service.</div><div class="notice"><b>Scout access</b><br>Questions about review, documents or team plans.</div><div class="notice"><b>Coach onboarding</b><br>Help setting up a team or understanding the workflow.</div></div></div></section>
 <main class="main">
 <section class="section grid cols3"><article class="card"><div class="icon green">01</div><h4 style="margin-top:10px">Product support</h4><p>Account access, product behaviour, coach onboarding and general ScoutLink help.</p></article><article class="card"><div class="icon">02</div><h4 style="margin-top:10px">Partnerships and media</h4><p>Commercial, football, event, sponsorship, press and collaboration enquiries.</p></article><article class="card"><div class="icon orange">03</div><h4 style="margin-top:10px">Trust and privacy</h4><p>Safeguarding, privacy requests, accessibility barriers and account concerns.</p></article></section>
 <section class="section form-card"><div class="section-title"><div><span class="pill green">Contact form</span><h2>Send a message.</h2></div><p>Your enquiry should be routed to the correct Stratex reviewer based on the selected reason.</p></div><div class="form-grid"><div class="field"><label>Reason</label><div class="input">Choose an enquiry type ▾</div></div><div class="field"><label>Your role</label><div class="input">Choose your role ▾</div></div><div class="field"><label>Name</label><div class="input">Your name</div></div><div class="field"><label>Email</label><div class="input">you@example.com</div></div><div class="field"><label>Phone</label><div class="input">Optional phone number</div></div><div class="field"><label>Organisation / team</label><div class="input">Organisation or team</div></div><div class="field full"><label>Message</label><div class="input textarea">Tell us what you need help with.</div></div></div><button class="btn primary block" style="margin-top:13px">Send message</button></section>
 <section class="section grid cols2"><article class="card"><span class="pill blue">What happens next</span><h3 style="font-size:22px;margin-top:10px">Your enquiry is reviewed and routed.</h3><p>Support, customer operations, growth or the appropriate trust reviewer should receive the information needed to respond.</p></article><article class="card"><span class="pill orange">Urgent concerns</span><h3 style="font-size:22px;margin-top:10px">Do not wait on a general contact form.</h3><p>Immediate danger should be reported to emergency services. Platform safety concerns should use the dedicated concern route.</p></article></section>
 </main>${footer()}${m?mobileSticky("Send Message"):""}</div>`;
}
function careersPage(m){
 return `<div class="page">${header("careers",m)}<section class="hero dark"><div><span class="pill dark">Careers at Stratex</span><h1>Build the future of football intelligence.</h1><p class="lead">Join the team behind ScoutLink, where product, data, customer operations, growth and football knowledge come together to help talent get seen with better evidence.</p><div class="hero-actions"><button class="btn primary">View Open Roles</button><button class="btn">Register Interest</button><button class="btn ghost" style="color:#fff;border-color:rgba(255,255,255,.18)">About Stratex</button></div><div class="hero-pills"><span class="pill dark">Early-stage ownership</span><span class="pill dark">Football technology</span><span class="pill dark">Flexible working</span></div></div><div class="hero-visual"><span class="pill dark">Work close to the product</span><h3 style="font-size:25px;margin:14px 0 7px">Build, learn and see the impact.</h3><p style="font-size:9px;color:#c5d3e2;line-height:1.55">Small teams create direct ownership across product decisions, users, football relationships and company growth.</p><div class="stats"><div class="stat"><b>Product</b><span>Build useful tools</span></div><div class="stat"><b>Football</b><span>Understand users</span></div><div class="stat"><b>Growth</b><span>Create opportunity</span></div></div></div></section>
 <main class="main">
 <section class="section"><div class="section-title"><div><span class="pill white">Open opportunities</span><h2>Join a growing football-technology company.</h2></div><p>Role availability can change, so the page should support both live vacancies and future-interest registration.</p></div><div class="role-list"><article class="role"><div><h4>Outreach Associate Internship</h4><span>Customer Operations · Coach acquisition and onboarding</span></div><span>Remote / UK</span><span>Flexible</span><button class="btn primary sm">View role</button></article><article class="role"><div><h4>Product and Data Opportunities</h4><span>Future roles across product, analytics and football intelligence</span></div><span>Future opening</span><span>Register interest</span><button class="btn sm">Register</button></article><article class="role"><div><h4>Football Operations Opportunities</h4><span>Future roles supporting evidence standards and football workflows</span></div><span>Future opening</span><span>Register interest</span><button class="btn sm">Register</button></article></div></section>
 <section class="section"><div class="section-title"><div><span class="pill white">Why join Stratex</span><h2>Work where the product, users and football problem meet.</h2></div></div><div class="grid cols3"><article class="card"><div class="icon green">01</div><h4 style="margin-top:10px">Real ownership</h4><p>Contribute close to company, product and customer decisions rather than several layers away.</p></article><article class="card"><div class="icon">02</div><h4 style="margin-top:10px">Football impact</h4><p>Help build more structured routes for overlooked grassroots players and teams.</p></article><article class="card"><div class="icon orange">03</div><h4 style="margin-top:10px">Cross-functional learning</h4><p>Develop across product, customer operations, growth, data and football workflows.</p></article></div></section>
 <section class="section grid cols2"><article class="card dark"><span class="pill dark">How we work</span><h3 style="font-size:24px;margin-top:11px">Clear ownership, honest feedback and practical delivery.</h3><p>Stratex is early-stage. People should be comfortable working across boundaries, learning quickly and improving the product from real user evidence.</p></article><article class="card"><span class="pill green">Hiring process</span><h3 style="font-size:24px;margin-top:11px">A focused process built around the role.</h3><p>Applications are reviewed for role fit, followed by relevant interviews or practical exercises rather than unnecessary stages.</p><div class="tag-list"><span class="pill grey">Application</span><span class="pill grey">Interview</span><span class="pill grey">Practical stage</span></div></article></section>
 <section class="section"><div class="section-title"><div><span class="pill white">Life at Stratex</span><h2>Build an ambitious company without pretending the work is finished.</h2></div></div><div class="timeline"><article class="timeline-item"><b>Stay close to users</b><p>Understand the coaches, scouts and families affected by product decisions.</p></article><article class="timeline-item"><b>Use evidence</b><p>Make decisions from research, product signals and football context.</p></article><article class="timeline-item"><b>Take responsibility</b><p>Own outcomes and communicate clearly when something needs to change.</p></article><article class="timeline-item"><b>Keep learning</b><p>Build skills through real work, feedback, courses and cross-functional exposure.</p></article></div></section>
 ${commonCTA("Do not see the right role yet?","Register your interest for future Stratex and ScoutLink opportunities.")}
 </main>${footer()}${m?mobileSticky("View Roles"):""}</div>`;
}

